# SPRING 2021
# Applied Machine Learning, HW 2

*Instructions:* Read all problems very carefully. Make sure that you are answering all questions included in a given problem. Every problem has a code cell inserted at the very end. You must show your solution in the code cell and run the cell by pressing the SHIFT and ENTER buttons simultaneously. The output of the cell must demonstrate the correctness of your solution. If you need to insert more code cells -- feel free to do so.

**Problem 1** You are given the following list:

In [ ]:
duplicates = ["ABC", 25, 89, "ABC", "ABC", 78, 25, 78, 78, 89, 89.0, "XYZ"]
print(duplicates)

['ABC', 25, 89, 'ABC', 'ABC', 78, 25, 78, 78, 89, 89.0, 'XYZ']


1. Create a new list called `unique` which is made of the unique entries present in the list above (the order of elements does not matter). 
2. Print `unique` to the screen.
3. Print a sentence saying "There are ??? unique entries in the original list!". The ??? part must be replaced with the actual number of unique elements. This number must be computed using a suitable function.

In [ ]:
duplicates = ["ABC", 25, 89, "ABC", "ABC", 78, 25, 78, 78, 89, 89.0, "XYZ"]
uniques = set(duplicates)
print(uniques)
print("there are " + str(len(uniques)) + " entries in the original list!")

{'ABC', 78, 89, 'XYZ', 25}
there are 5 entries in the original list!


**Problem 2** You are given a list storing four town names:

In [ ]:
towns = ["pella", "oskaloosa", "knoxville", "newton"]

Create a new list `towns_cap` in which each of these names is capitalized. Do it in the most efficient way (invoke list comprehension).

In [ ]:
towns = ["pella", "oskaloosa", "knoxville", "newton"]
towns_cap = [i.upper() for i in towns]
print(towns_cap)

['PELLA', 'OSKALOOSA', 'KNOXVILLE', 'NEWTON']


**Problem 3** You are given a string variable `my_college` which is equal to "Central College":

In [ ]:
my_college = "Central College"
print(my_college)

Central College


Strating from this variable produce the following output:

`C*e*N*t*R*a*L* *C*o*L*l*E*g*E*`

*Hint:* I recommend you define a new integer variable, say `i`, that will be playing the role of a counter. Initialize `i` with zero and increment it by 1 at each iteration.

In [ ]:
my_college = "Central College"
my_new = ""
for i in range(len(my_college)):
  if i  % 2 == 0:
    my_new += my_college[i].upper()
    my_new += "*"
  elif i % 2 != 0:
    my_new += my_college[i]
    my_new += "*"
print(my_new)

 


C*e*N*t*R*a*L* *C*o*L*l*E*g*E*


**Problem 4** The prices of 5 different items are stored in a dictionary `prices`:

In [ ]:
prices = {'ice cream': 1.50, 'cookies': 3.34, 'bread': 2.25, 'tea': 3.89, 'ham': 4.03}

1. Pick one of the items that you would like to call your favorite. Store the name of this item in a variable called "favorite_item".
2. Iterate through this dictionary to print its content to the screen in the form of the following sentence: "The price of ??? is ??? dollars." where the ??? part should be replaced with the proper item name and the price value. For  your favorite item, the sentence above should be ammended with a phrase "I really like ???!" where, again, the ??? part must be replace with the name of your favorite item. Be sure that there is a space between the sentences!

In [ ]:
prices = {'ice cream': 1.50, 'cookies': 3.34, 'bread': 2.25, 'tea': 3.89, 'ham': 4.03}
favorite_item = 'tea'
for x, y in prices.items():
  print("the price of "+ x +" is "  + str(y) +" dollars" + "my favorite item is "+ favorite_item )


the price of ice cream is 1.5 dollarsmy favorite item is tea
the price of cookies is 3.34 dollarsmy favorite item is tea
the price of bread is 2.25 dollarsmy favorite item is tea
the price of tea is 3.89 dollarsmy favorite item is tea
the price of ham is 4.03 dollarsmy favorite item is tea


**Problem 5** Write a Python function called `spell_backwards` that takes a list of strings as an input and returns another list that contains all elements of the original list written in reverse and capitalized (only the first character must be capitalized, all others must be lowercase). For example, if the input is a list of strings `["Alexey", "John", "Anna"]` then the output must be `["Yexela", "Nhoj", "Anna"]`. Note that "Anna" is a *palindrome* which is a word, phrase, or sentence that reads the same backward or forward.

Demonstrate that the function works as expected by feeding it the string `["Alexey", "John", "Anna"]`.

In [ ]:
namelist = ["Alexey", "John", "Anna"]
def spell_backwards(name_list):
  newlist = []
  for i in name_list:
    string = i[::-1]
    string = string.capitalize()
    newlist.append(string)
  return newlist
spell_backwards(namelist)

['Yexela', 'Nhoj', 'Anna']

**Problem 6** Write a program that prints the numbers from 1 to 100. But for multiples of three print “Fizz” instead of the number and for the multiples of five print “Buzz”. For numbers which are multiples of both three and five print “FizzBuzz”. (This is the famous *FizzBuzz* problem which is a very popular interview question for programming jobs.)

In [ ]:
for i in range(0,100):
  if i % 3 == 0:
    print("Fizz")
  elif i % 5 == 0:
      print("Buzz")
  else:
      print(i)

**Problem 7** Write a Python function called `string_transform` that takes a single string as its input and does the following:
1. If the input sring contans an odd number of characters then all characters of the string must be coverted to uppercase. 
2. If the input string contains an even number of characters then the function returns a list whose elements are the characters of the input string; the order of these elements must be the same as the order of the corresponding characters in the input string.
3. The result of the transformation must be printed to the screen and returned as an output of the function.

Test your function with the following strings: `abracadabra` and `palindrome`. 

In [ ]:
a = 'abracadabra'
b = 'palindrome'
def string_transform(string):
  if len(string) % 2 != 0:
    print(string.upper())
  else:
    return string.split()
string_transform(a)
string_transform(b)

ABRACADABRA


['palindrome']

**Probelem 8** Create a NumPy array of all even numbers from 2 to 50 (inclusive) using 3 different methods:
1. Starting with a Python list created using conditional list comprehension and the `range(2, 51)` function (you are not allowed to change the argument of the function!). Note that here, in your conditional list comprehension, there will be no `else` statement. In this case the `if` statement is placed not before but after the `for` statement (see, for example, [this reference](https://riptutorial.com/python/example/767/conditional-list-comprehensions)).
2. Starting with the `range()` function (here you can use any arguments you like for the function).
3. Using an appropriate NumPy built-in function.


In [ ]:
import numpy as np
#method 1
list_1 = [i for i in range(2,51) if i % 2 == 0]
arr_1 = np.array(list_1)

#method 2
arr_2 = np.array(range(2,51,2))

#method 3
arr_3 = np.arange(2,51,2)


**Problem 9** 
1. Create a NumPy array called `fives` which has the form of a matrix with 3 rows and 4 columns and whose elements are all equal to 5.
2. Create another NumPy array of random integers from 3 to 8 called `rand_ints` with the same number of rows and columns.
3. Print both arrays to the screen and then try adding them using the `+` operator. Did you get any error message?
4. Inspect the result: does it make sense to you (it should)?
5. Now let's try to do the same with lists. Try adding together two lists, `[1, 2, 3]` and `[4, 5, 6]` using the same `+` operator. Did you get any error message? Does the `+` operator work the same or differently with lists?

In [12]:
import numpy as np
import random 
fives = np.full((3,4), 5)
rand_ints = np.full((3,4), random.randint(3,8) )
print(fives)
print("+")
print(rand_ints)
print("=")
print(fives + rand_ints)
print("")
list_1 = [1,2,3]
list_2 = [4,5,6]
print(list_1+list_2)
#the '+' operator works differently with lists as it concatenates, for arrays the operator adds the integers

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
+
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
=
[[11 11 11 11]
 [11 11 11 11]
 [11 11 11 11]]

[1, 2, 3, 4, 5, 6]
