# SPRING 2021
# Applied Machine Learning, HW 3

*Instructions:* Read all problems very carefully. Make sure that you are answering all questions included in a given problem. Every problem has a code cell inserted at the very end. You must show your solution in the code cell and run the cell by pressing the SHIFT and ENTER buttons simultaneously. The output of the cell must demonstrate the correctness of your solution. If you need to insert more code cells -- feel free to do so.

**Problem 1** 
1. Set the NumPy random seed equal to a value of 2021 (the current year). (Don't forget to import the NumPy library first!)
2. Then create a 3 by 5 (rows$\times$columns -- from now on this is going to be our standard convention) NumPy array of random floating point numbers uniformly distributed from 30 to 50 (inclusive). Call this array `rand_floats` and print it to the screen. 
3. Next, set the same random seed again and create a 3 by 5 NumPy array of random values pulled from the normal distribution of mean 40 and standard deviation 10 (use the built-in help system if you are not sure about the syntax). Call this array `rand_norm` and print it to the screen.
4. Measure the average time it takes to add these two arrays using the `+` operator (do it is a separate code cell).
5. Add the arrays using the `+` operator and store  the result in a new array called `floats_plus_norm`.
5. Print `floats_plus_norm` to the screen.

In [ ]:
import numpy as np
np.random.seed(2021)
rand_floats = np.random.uniform(30,50, size=(3,5))
np.random.seed(2021)
rand_norm = np.random.normal(loc=40.0,scale=10.0,size=(3,5))
floats_plus_norm = rand_floats + rand_norm
print(floats_plus_norm)

[[97.0056561  91.42749594 68.59442944 68.18825355 95.50362394]
 [65.50820464 84.88844474 91.50852694 84.30734771 89.90775094]
 [73.17995637 62.7918911  93.33807685 83.35866106 52.65537532]]


In [ ]:
%timeit rand_norm + rand_floats

**Problem 2** 

1. Set the random seed equal to 2021.
2. Create a one-dimensional NumPy array of 20 random integers uniformly distributed between 5 and 15 (inclusive) and print it to the screen.
3. Reshape the array into a 4 by 5 matrix. Call the new array `rand_2d` and print it to the screen. 
4. If you set your random seed correctly, you should see that `rand_2d` has only one element whose value is equal to 15. Use NumPy indexing to save this element of the array into a new variable called `num_15`. Print `num_15` to the screen.
5. Select a continuous rectangular slice from the `rand_2d` array such that
  * the top left corner of the slice contains number 13,
  * the bottom right corner of the slice contains number 12.

  Save the slice into a variable called `slice_2d` and print this variable to the screen.
6. Set the top left element of `slice_2d` to be equal to 500 and print it to the screen.
7. Print `rand_2d` to the screen. Does it look the same? If not, what happened?

In [ ]:
import numpy as np
np.random.seed(2021)
rand_1d = np.random.randint(5,16, size=20)
rand_2d = rand_1d.reshape((4,5))
print(rand_2d)
num_15 = rand_2d[3,2]
print('\n')
print(num_15)
slice_2d = rand_2d[1:3,1:4]
print('\n')
print(slice_2d)
slice_2d[0,0] = 500
print('\n')
print(slice_2d)
print('\n')
print(rand_2d)
#what happened was that while i edited my slice i still edited the array. The slice was a sub-array of sorts.

[[ 9 10 14  5 11]
 [10 13 11 11 11]
 [11  6 10 12  6]
 [ 6 10 15  7  5]]


15


[[13 11 11]
 [ 6 10 12]]


[[500  11  11]
 [  6  10  12]]


[[  9  10  14   5  11]
 [ 10 500  11  11  11]
 [ 11   6  10  12   6]
 [  6  10  15   7   5]]


**Problem 3** 
1. Use an appropriate NumPy function to create an increasing sequence of consecutive positive integers from 0 to 19 (inclusive). Store this sequence in a variable called `pos` and print this variable to the screen.
2. In a similar fashion, create a decreasing sequence of consecutive negative integers from 0 to -19 (inclusive). Store this sequence in a variable called `neg` and print this variable to the screen. 
3. To check that your sequences are correct, add `pos` and `neg` together -- the result must be an array of 20 zeros.
4. Concatenate the first 4 elements of `pos` with the last 3 elements of `neg` (in this order) and print the result to the screen.
5. Reshape both `pos` and `neg` into a 5 by 4 matrices called `pos_mat` and `neg_mat`. Print the matrices to the screen.
6. Stack matrices row-wise placing `pos_mat` on top. The result must be a new 10 by 4 matrix. Print this matrix to the screen.
7. Stack matrices column-wise placing `neg_mat` at the leftmost position. The result must be a new 5 by 8 matrix. Print this matrix to the screen.

In [ ]:
import numpy as np
pos = np.arange(0,20)
print(pos)
neg = np.arange(0,-20,-1)
print(neg)
print(pos + neg)
print('\n')
np.concatenate((pos[0:5],neg[-3:]))
pos_mat = pos.reshape((5,4))
neg_mat = neg.reshape((5,4))
print('\n')
print(pos_mat)
print('\n')
print(neg_mat)
print('\n')
print(np.vstack((pos_mat,neg_mat)))
print('\n')
print(np.hstack((pos_mat,neg_mat)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15 -16 -17
 -18 -19]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


[[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]
 [-12 -13 -14 -15]
 [-16 -17 -18 -19]]


[[  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]
 [ 16  17  18  19]
 [  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]
 [-12 -13 -14 -15]
 [-16 -17 -18 -19]]


[[  0   1   2   3   0  -1  -2  -3]
 [  4   5   6   7  -4  -5  -6  -7]
 [  8   9  10  11  -8  -9 -10 -11]
 [ 12  13  14  15 -12 -13 -14 -15]
 [ 16  17  18  19 -16 -17 -18 -19]]


**Problem 4** 
1. Set the random seed equal to 2021 and create a one-dimensional array of 10 random integers uniformly distributed from 0 to 9 (inclusive). Call it `pos_10` and print it to the screen.
2. Set the random seed equal to 2021 again and create another one-dimensional array of 10 random integers uniformly distributed from -9 to 0 (inclusive). Call it `neg_10` and print it to the screen.
3. Imagine that we are only allowed to change the order of the elements in the two arrays in a synchronous fashion or *in unison*. This means that every time when we move an element of one array from some index $i$ to some other index $j$ we must simultaneously move the $i^{\text{th}}$ element of the other array to the $j^{\text{th}}$ position. Now, you are asked to arrange the values in the `pos_10` array in the increasing order, from the smallest to the largerst and change the order of `neg_10` according to the above-mentioned rule. Perform this rearrangement and demonstrate how it affects both of these arrays.
4. Create a new 2 by 2 NumPy array whose first colum is filled with the very first element of `pos_10` and the last columns is filled with the very last element of `pos_10` (use the unsorted version of this array). *Hint:* Use fancy indexing!

In [11]:
import numpy as np
np.random.seed(2021)
pos_10 = np.random.randint(0,10,size=10)
print(pos_10)
np.random.seed(2021)
neg_10 = np.random.randint(-9,0,size=10)
print('\n')
print(neg_10)
print('\n')
pos_10_s = np.sort(pos_10,axis=-1,kind='heapsort')
neg_10_s = np.sort(neg_10,axis=-1,kind='heapsort')
print(pos_10_s)
print(neg_10_s)
print('\n')
new_arr = np.array( [ [pos_10[0], pos_10[0]], [pos_10[9], pos_10[9] ] ])
print(new_arr)

[4 5 9 0 6 5 8 6 6 6]


[-5 -4 -9 -3 -4 -1 -3 -3 -3 -3]


[0 4 5 5 6 6 6 6 8 9]
[-9 -5 -4 -4 -3 -3 -3 -3 -3 -1]


[[4 4]
 [6 6]]
